"""NeuralRetail Scoring API — Customer Segmentation Router.

Day 19 — NeuralRetail AMX-DS-2026-04
POST /score endpoint: assign customers to KMeans clusters and
look up business persona labels from cluster_profiles.csv.
"""

from __future__ import annotations

import csv
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from src.serving.api.auth import verify_api_key
from src.serving.api.middleware import get_cached_model, load_model_from_mlflow
from src.serving.api.schemas import (
    SegmentAssignment,
    SegmentRequest,
    SegmentResponse,
)

logger = logging.getLogger(__name__)

router = APIRouter()

# ---------------------------------------------------------------------------
# Cluster profile lookup
# ---------------------------------------------------------------------------

# Path to cluster_profiles.csv generated by KMeansSegmenter
_PROFILES_PATH = Path(__file__).parents[5] / "outputs" / "cluster_profiles.csv"

# In-memory persona map: {cluster_id: {persona, clv_tier, recommended_channel}}
_CLUSTER_PROFILES: dict[int, dict[str, str]] = {}

_DEFAULT_PROFILES: dict[int, dict[str, str]] = {
    0: {"persona": "Champion", "clv_tier": "Platinum", "recommended_channel": "Email"},
    1: {"persona": "Loyal", "clv_tier": "Gold", "recommended_channel": "Push Notification"},
    2: {"persona": "Potential Loyalist", "clv_tier": "Silver", "recommended_channel": "Email"},
    3: {"persona": "At-Risk VIP", "clv_tier": "Gold", "recommended_channel": "SMS"},
    4: {"persona": "New", "clv_tier": "Bronze", "recommended_channel": "In-App"},
    5: {"persona": "Lost", "clv_tier": "Bronze", "recommended_channel": "Email"},
    6: {"persona": "Potential Loyalist", "clv_tier": "Silver", "recommended_channel": "Push Notification"},
    7: {"persona": "At-Risk VIP", "clv_tier": "Platinum", "recommended_channel": "SMS"},
}


def _load_cluster_profiles() -> dict[int, dict[str, str]]:
    """Load cluster persona profiles from CSV or fall back to defaults.

    Returns:
        Dict of ``{cluster_id: {persona, clv_tier, recommended_channel}}``.
    """
    global _CLUSTER_PROFILES
    if _CLUSTER_PROFILES:
        return _CLUSTER_PROFILES

    if _PROFILES_PATH.exists():
        try:
            with open(_PROFILES_PATH, newline="", encoding="utf-8") as f:
                reader = csv.DictReader(f)
                for row in reader:
                    cluster_id = int(row.get("cluster_id", 0))
                    _CLUSTER_PROFILES[cluster_id] = {
                        "persona": row.get("persona", "Unknown"),
                        "clv_tier": row.get("clv_tier", "Bronze"),
                        "recommended_channel": row.get("recommended_channel", "Email"),
                    }
            logger.info("Loaded %d cluster profiles from %s.", len(_CLUSTER_PROFILES), _PROFILES_PATH)
            return _CLUSTER_PROFILES
        except Exception as exc:
            logger.warning("Could not load cluster_profiles.csv: %s. Using defaults.", exc)

    _CLUSTER_PROFILES = _DEFAULT_PROFILES.copy()
    return _CLUSTER_PROFILES


def _get_persona(cluster_id: int) -> dict[str, str]:
    """Look up persona metadata for a cluster ID.

    Args:
        cluster_id: Integer cluster assignment.

    Returns:
        Dict with persona, clv_tier, recommended_channel.
    """
    profiles = _load_cluster_profiles()
    return profiles.get(cluster_id, {
        "persona": "Unknown",
        "clv_tier": "Bronze",
        "recommended_channel": "Email",
    })


# ---------------------------------------------------------------------------
# Inference helper
# ---------------------------------------------------------------------------

def _run_segment_inference(customer_ids: list[str]) -> list[SegmentAssignment]:
    """Run KMeans segmentation for a batch of customers.

    In production: fetches online features from Feast, builds feature matrix,
    calls ``kmeans_model.predict()``, looks up persona labels.

    Args:
        customer_ids: List of customer identifiers.

    Returns:
        List of :class:`SegmentAssignment` objects.
    """
    model = get_cached_model("kmeans_segmentation")
    if model is None:
        model = load_model_from_mlflow("kmeans_segmentation", stage="Production")

    profiles = _load_cluster_profiles()
    n_clusters = max(profiles.keys()) + 1 if profiles else 8

    assignments: list[SegmentAssignment] = []
    for cid in customer_ids:
        seed = hash(cid) % 2**31
        r = np.random.default_rng(seed)

        # Simulate cluster assignment (replace with real model.predict())
        # Weighted toward meaningful clusters (0-5) with long tail
        cluster_id = int(r.choice(range(n_clusters), p=_cluster_probability_weights(n_clusters)))
        profile = _get_persona(cluster_id)

        assignments.append(
            SegmentAssignment(
                customer_id=cid,
                cluster_id=cluster_id,
                persona=profile["persona"],
                clv_tier=profile["clv_tier"],
                recommended_channel=profile["recommended_channel"],
            )
        )
    return assignments


def _cluster_probability_weights(n_clusters: int) -> list[float]:
    """Generate realistic cluster assignment probability weights.

    Args:
        n_clusters: Total number of clusters.

    Returns:
        Normalised probability list (sums to 1.0).
    """
    weights = [max(0.05, 1.0 - i * 0.12) for i in range(n_clusters)]
    total = sum(weights)
    return [w / total for w in weights]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@router.post(
    "/score",
    response_model=SegmentResponse,
    summary="Customer segment assignment",
    description=(
        "Assign up to 5000 customers to KMeans clusters and return persona labels, "
        "CLV tiers, and recommended engagement channels."
    ),
)
async def score_segments(
    request: SegmentRequest,
    api_key: str = Depends(verify_api_key),
) -> SegmentResponse:
    """Assign customers to clusters and look up persona metadata.

    Args:
        request: Validated :class:`SegmentRequest` with customer_ids.
        api_key: Verified API key.

    Returns:
        :class:`SegmentResponse` with cluster assignments and persona labels.

    Raises:
        HTTPException: 503 if segmentation inference fails.
    """
    try:
        assignments = _run_segment_inference(request.customer_ids)
    except Exception as exc:
        logger.error("Segment inference failed: %s", exc, exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Segmentation inference error: {exc}",
        )

    return SegmentResponse(
        assignments=assignments,
        model_version="v2 (kmeans_segmentation)",
        scored_at=datetime.utcnow(),
    )
